import { MD3LightTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#667eea',
    primaryContainer: '#e8eaf6',
    secondary: '#764ba2',
    secondaryContainer: '#f3e5f5',
    tertiary: '#f093fb',
    tertiaryContainer: '#fce4ec',
    surface: '#ffffff',
    surfaceVariant: '#f5f5f5',
    background: '#fafafa',
    error: '#f44336',
    errorContainer: '#ffebee',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onTertiary: '#ffffff',
    onSurface: '#212121',
    onSurfaceVariant: '#757575',
    onBackground: '#212121',
    onError: '#ffffff',
    outline: '#e0e0e0',
    outlineVariant: '#f0f0f0',
    inverseSurface: '#2f2f2f',
    inverseOnSurface: '#ffffff',
    inversePrimary: '#bbdefb',
    shadow: '#000000',
    scrim: '#000000',
    surfaceDisabled: 'rgba(33, 33, 33, 0.12)',
    onSurfaceDisabled: 'rgba(33, 33, 33, 0.38)',
    backdrop: 'rgba(33, 33, 33, 0.4)',
  },
};
